### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by NikitaZhevnitskiy** [jeqo/zipkin-storage-kafka#10]
Test failings and problems with releasing lock

```
[ERROR] Tests run: 3, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 52.894 s <<< FAILURE! - in zipkin2.storage.kafka.KafkaStorageIT
[ERROR] should_consume_spans(zipkin2.storage.kafka.KafkaStorageIT)  Time elapsed: 22.413 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
        at zipkin2.storage.kafka.KafkaStorageIT.should_consume_spans(KafkaStorageIT.java:75)

[ERROR] should_get_service(zipkin2.storage.kafka.KafkaStorageIT)  Time elapsed: 11.385 s  <<< ERROR!
java.lang.RuntimeException: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /private/tmp/lucene-index/write.lock
        at zipkin2.storage.kafka.KafkaStorageIT.should_get_service(KafkaStorageIT.java:108)
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /private/tmp/lucene-index/write.lock
        at zipkin2.storage.kafka.KafkaStorageIT.should_get_service(KafkaStorageIT.java:108)

[ERROR] should_get_trace(zipkin2.storage.kafka.KafkaStorageIT)  Time elapsed: 11.612 s  <<< ERROR!
java.lang.RuntimeException: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /private/tmp/lucene-index/write.lock
        at zipkin2.storage.kafka.KafkaStorageIT.should_get_trace(KafkaStorageIT.java:87)
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /private/tmp/lucene-index/write.lock
        at zipkin2.storage.kafka.KafkaStorageIT.should_get_trace(KafkaStorageIT.java:87)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KafkaStorageIT.should_consume_spans:75 expected:<1> but was:<0>
[ERROR] Errors: 
[ERROR]   KafkaStorageIT.should_get_service:108 » Runtime org.apache.lucene.store.LockOb...
[ERROR]   KafkaStorageIT.should_get_trace:87 » Runtime org.apache.lucene.store.LockObtai...
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 2, Skipped: 0
```

**Comment by NikitaZhevnitskiy** [comment]
ref: #12

**Comment by NikitaZhevnitskiy** [comment]
#12

**Comment by jeqo** [comment]
#12 merged. thanks again!
